namespace: mon

generators:
- |-
  apiVersion: v1
  kind: krmFn
  metadata:
    name: local
    annotations:
      config.kubernetes.io/function: |
        exec:
          path: "fnRenderJsonnet"
  spec:
    jpath: ../vendor
    file: ./mixin-simple.jsonnet
